In [63]:
import numpy as np
arr1 = np.arange(10)
arr1

array([0, 1, 2, ..., 7, 8, 9])

In [64]:
np.set_printoptions(threshold=6)
alpha = np.arange(15)
alpha

array([ 0,  1,  2, ..., 12, 13, 14])

In [65]:
bill = np.array([(1.5,2,3), (4,5,6)])
bill

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [66]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

In [67]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [68]:
cmp = np.array( [ [1,2], [3,4] ], dtype=complex )
cmp


array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [69]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [70]:
np.ones( (2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [71]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [72]:
c = np.arange(24).reshape(2,3,4)       
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [73]:
index = np.where((a >= 5) & (a <= 10))
a[index]

array([5])

In [74]:
b = np.arange(12).reshape(4,3)       
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [75]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, ..., -1,  8, -1])

In [76]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)

[0 1 2 ... 7 8 9]


In [77]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [78]:
alpha = np.arange(3)
alpha

array([0, 1, 2])

In [79]:
np.sqrt(alpha)

array([0.  , 1.  , 1.41])

In [80]:
arr = np.arange(10)
arr.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [81]:
no = np.arange(10)**3
no

array([  0,   1,   8, ..., 343, 512, 729], dtype=int32)

In [82]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate([a, b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [83]:
no[:6:2] = 1000
no

array([1000,    1, 1000, ...,  343,  512,  729], dtype=int32)

In [84]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate([a, b], axis=1)

array([[0, 1, 2, ..., 1, 1, 1],
       [5, 6, 7, ..., 1, 1, 1]])

In [85]:
a = np.array([[ 0,  1,  2,  3],[ 4,  5,  6,  7],[ 8,  9, 10, 11]])
b = a            # no new object is created
b is a 

True

In [86]:
b = np.arange(10)
for element in b.flat:
    print(element)

0
1
2
3
4
5
6
7
8
9


In [87]:
a = np.arange(5)
a[[0,0,2]]+=1
a

array([1, 1, 3, 3, 4])

In [88]:
a = np.arange(12).reshape(3,4)
b = a > 4
b  

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [89]:
np.set_printoptions(precision=2)
np.random.seed(100)
a = np.random.uniform(1,50, 20)
np.clip(a, a_min=10, a_max=30)


array([27.63, 14.64, 21.8 , ..., 10.  , 30.  , 14.43])

In [90]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)
print(a.argsort())

[ 4 13  5 ...  3 10 15]


In [91]:
a[a.argsort()][-5:]

array([41.  , 41.47, 42.39, 44.67, 48.95])

In [92]:
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr

array([[ 9,  9,  4, ...,  3,  6,  3],
       [ 3,  3,  2, ..., 10,  7,  3],
       [ 5,  2,  6, ...,  8,  2,  2],
       [ 8,  8,  1, ...,  3,  6,  9],
       [ 2,  1,  8, ...,  3,  6,  2],
       [ 9,  2,  6, ...,  6,  1, 10]])

In [93]:
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr

array([[ 9,  9,  4, ...,  3,  6,  3],
       [ 3,  3,  2, ..., 10,  7,  3],
       [ 5,  2,  6, ...,  8,  2,  2],
       [ 8,  8,  1, ...,  3,  6,  9],
       [ 2,  1,  8, ...,  3,  6,  2],
       [ 9,  2,  6, ...,  6,  1, 10]])

In [94]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
np.amax(a, axis=1)

array([9, 8, 6, 3, 9])

In [95]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a

array([[9, 9, 4],
       [8, 8, 1],
       [5, 3, 6],
       [3, 3, 3],
       [2, 1, 9]])

In [96]:
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print('Array: ', a)

Array:  [0 0 3 ... 2 2 2]


In [97]:
arr[arr % 2 == 1] = -1
arr

array([[-1, -1,  4, ..., -1,  6, -1],
       [-1, -1,  2, ..., 10, -1, -1],
       [-1,  2,  6, ...,  8,  2,  2],
       [ 8,  8, -1, ..., -1,  6, -1],
       [ 2, -1,  8, ..., -1,  6,  2],
       [-1,  2,  6, ...,  6, -1, 10]])